/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AftercareRouteImport } from './routes/aftercare'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LegalRouteImport } from './routes/legal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AftercareRoute = AftercareRouteImport.update({
  id: '/aftercare',
  path: '/aftercare',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aftercare': typeof AftercareRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/legal': typeof LegalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aftercare' | '/booking' | '/gallery' | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aftercare' | '/booking' | '/gallery' | '/legal'
  id: '__root__' | '/' | '/aftercare' | '/booking' | '/gallery' | '/legal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AftercareRoute: typeof AftercareRoute
  BookingRoute: typeof BookingRoute
  GalleryRoute: typeof GalleryRoute
  LegalRoute: typeof LegalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aftercare': {
      id: '/aftercare'
      path: '/aftercare'
      fullPath: '/aftercare'
      preLoaderRoute: typeof AftercareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AftercareRoute: AftercareRoute,
  BookingRoute: BookingRoute,
  GalleryRoute: GalleryRoute,
  LegalRoute: LegalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
